#!/bin/bash

function Flex {
    echo -e " \uf2dc" "voidz" 
}

function p_time {
    time="$(date +"%I:%M %p")"
    printf "%s" "$time"
}

function battery {
    bat_dir=/sys/class/power_supply/BAT0
    read -r capacity < "$bat_dir/capacity"
    read -r status   < "$bat_dir/status"
    echo -e " \uf244 $capacity "
}

function work {
    echo -e "%{l}$(Flex) %{c}$(p_time)%{r}$(battery) "
    sleep 2s
}
while true;do
    work
done
